### ISSUE TITLE
Failed to work with gitkraken

### ISSUE THREAD

**Issue by danielporto** [jlesage/docker-baseimage-gui#39] opened 2020-08-20 14:33 UTC
Dockerfile:
```
FROM jlesage/baseimage-gui:debian-10

# Install gitkraken.
RUN apt update \
    && apt install -y wget \
    && wget https://release.gitkraken.com/linux/gitkraken-amd64.deb  -P /tmp \
    && apt remove -y wget \
    && apt install -y gconf2 gconf-service libgtk2.0-0 libnotify4 libnss3 gvfs-bin xdg-utils libxss1 libasound2 procps\
    && dpkg -i /tmp/gitkraken-amd64.deb \
    && rm -rf /var/cache/apt /tmp/gitkraken-amd64.deb

# Copy the start script.
COPY startapp.sh /startapp.sh

# Set the name of the application.
ENV APP_NAME="GitKraken"
```
----
startapp.sh
```
#!/bin/sh
exec /usr/bin/gitkraken
```
---
docker run --rm -p 5800:5800 -p 5900:5900 gitkraken
Result:
```
[services.d] starting statusmonitor...
[services.d] starting logmonitor...
[statusmonitor] no file to monitor: disabling service...
[services.d] starting app...
[logmonitor] no file to monitor: disabling service...
[app] starting GitKraken...
[services.d] done.
**Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted**
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping logmonitor...
[services.d] stopping statusmonitor...
[services.d] stopping openbox...
[services.d] stopping certsmonitor...
[services.d] stopping nginx...
[services.d] stopping x11vnc...
caught signal: 15
20/08/2020 14:30:59 deleted 40 tile_row polling images.
[services.d] stopping xvfb...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
Any hint?

**Comment by jlesage** [comment] 2020-08-25 03:13
The problem is:
```
**Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted**
```
The app is using a feature not allowed by default by docker.  To confirm, try to run the container in privileged mode to see if it then works.

Is the app based on electron?  If yes, you may try to add the `--no-sandbox` parameter to `gitkraken`.

**Comment by Casburggraaf** [comment] 2022-04-08 10:44
@danielporto Did you ever get this to work?

**Comment by jlesage** [comment] 2024-02-17 22:16
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2024-02-17 22:16 UTC
