### ISSUE TITLE
enable clipboard

### ISSUE THREAD

**Issue by maniasso** [jlesage/docker-baseimage-gui#23] opened 2019-07-18 14:02 UTC
Is there a way to enable clipboard at the image? I want to paste into the application and copy from the application running in the container

**Comment by jlesage** [comment] 2019-07-21 00:52
This is already supported.  With the provided web interface, you have a "Clipboard" button you can use.

**Comment by maniasso** [comment] 2019-07-22 10:52
In fact I've been using Firefox but I was able only to copy from the container, I can't paste into the application, is there a way to enable that?

**Comment by jlesage** [comment] 2019-07-22 11:19
This should also work:  when you click the Clipboard button, writing something into the box and then click the Submit button.  The content is then available to your app to paste (via ctrl-v and/or right click-paste depending on the app).

**Comment by maniasso** [comment] 2019-07-22 11:58
I tried with Firefox and Chrome and no one was able to paste, I was looking
for logs, but I couldn't find anything that could help understand why the
paste is not working... If you have any clue where I can look for logs I
appreciate. I tried the /tmp and /config and nothing useful that could
help....

Em seg, 22 de jul de 2019 às 08:19, Jocelyn Le Sage <
notifications@github.com> escreveu:

**Comment by maniasso** [comment] 2019-07-22 11:59
I tried with Firefox and Chrome and no one was able to paste, I was looking for logs, but I couldn't find anything that could help understand why the paste is not working... If you have any clue where I can look for logs I appreciate. I tried the /tmp and /config and nothing useful that could help....

**Comment by jlesage** [comment] 2019-07-23 01:08
You can try to check if the issue is with your application by installing and running something like `xterm` and verify if pasting into it is working.

Else, you can also look at the log from the console of your browser's developper tools.  You can enable debug logs by adding `?logging=debug` to your access url.  For example: `http://192.168.1.1:5800/?logging=debug`

**Comment by maniasso** [comment] 2019-07-23 15:43
I just figured out the issue with "paste"option, it does work, but only pressing scroll button at mouse, it automatically paste into container when I press it. 
By pressing right button it doesn't work, do you know if there's a way to change it? This happen using basic container with xterm.

**Comment by jlesage** [comment] 2019-09-23 22:44
This seems to be related to the app itself.  For example, the behaviour you describe with xterm is the same when running the app in a native Ubuntu environment.

**Comment by f4bio79** [comment] 2022-04-07 14:15
> I just figured out the issue with "paste"option, it does work, but only pressing scroll button at mouse, it automatically paste into container when I press it. By pressing right button it doesn't work, do you know if there's a way to change it? This happen using basic container with xterm. I'm using the image with alpine linux.

hello Maniasso
can you explain how you manage to use that function
I tried to write something in the clipboard, then I pressed "submit" , but using the right click, or the combination CTRL+V doesn't paste anything inside the firefox docker
I even tried using ALT button and then selecting EDIT --> PASTE, but the "paste" button is grey and not available

thanks in advance for any clarification

**Comment by jlesage** [comment] 2024-02-17 22:12
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2024-02-17 22:12 UTC
