### ISSUE TITLE
Maximize Windows Does not Work Sometimes

### ISSUE THREAD

**Issue by smcoder0707** [jlesage/docker-baseimage-gui#111] opened 2023-09-08 18:36 UTC
For some apps (Using wine), the window maximization does not work properly. It leaves black screen at the right side. I'm sure that openbox is able to select the window based on my configuration (Because window decorations are hidden as you can see in the image below)
![image](https://github.com/jlesage/docker-baseimage-gui/assets/91800024/5f6309a6-4c01-40f5-b581-9888c7eea86e)

Note that, I can manually maximize the window using tools like wmctrl or xdotool but that only works If I have the VNC webpage open and I'm logged into it.

Any ideas about what could be wrong here?

**Comment by jlesage** [comment] 2023-09-10 17:47
With Wine, remote resizing of the application's window won't adjust beyond the size defined by `DISPLAY_WIDTH` and `DISPLAY_HEIGHT`.  Workaround is to adjust these variables accordingly.  I didn't find the root cause of this issue, but looks like something specific to Wine.

**Comment by jlesage** [comment] 2024-11-22 00:39
Closing this issue. Please re-open if needed.

**Closed by jlesage** 2024-11-22 00:39 UTC
