### ISSUE TITLE
申请添加支持Freefilesync

### ISSUE THREAD

**Issue by gzxiexl** [jlesage/docker-baseimage-gui#69] opened 2022-07-26 07:06 UTC
FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files. Instead of copying every file every time, FreeFileSync determines the differences between a source and a target folder and transfers only the minimum amount of data needed. FreeFileSync is Open Source software, available for Windows, macOS, and Linux.

https://freefilesync.org/

申请添加这个软件的docker镜像，谢谢

**Comment by jlesage** [comment] 2022-10-14 11:38
Duplicate of #60.

**Closed by jlesage** 2022-10-14 11:38 UTC
